/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grame_midishare_Midi */

#ifndef _Included_grame_midishare_Midi
#define _Included_grame_midishare_Midi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grame_midishare_Midi
 * Method:    AddField
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AddField
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AddSeq
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AddSeq
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    ApplySeq
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ApplySeq
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AvailEv
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_AvailEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Call
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Call
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    ClearSeq
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ClearSeq
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Close
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Connect
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Connect
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CopyEv
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CopyEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountAppls
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountAppls
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountDTasks
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountDTasks
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountEvs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountEvs
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountFields
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountFields
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    DTask
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_DTask
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Exec1DTask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Exec1DTask
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Ext2IntTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Ext2IntTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    FlushDTasks
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FlushDTasks
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    FlushEvs
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FlushEvs
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    ForgetTask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ForgetTask
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeCell
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeCell
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeEv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeSeq
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeSeq
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeSpace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_FreeSpace
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetApplAlarm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetApplAlarm
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetEv
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetExtTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetExtTime
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetField
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetField
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetFilter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetFilter
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetIndAppl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetIndAppl
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_grame_midishare_Midi_GetName
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetNamedAppl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetNamed
  (JNIEnv *, jclass, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetPortState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetPortState
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetRcvAlarm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetRcvAlarm
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetSyncInfo
 * Signature: (Lgrame/midishare/SyncInfo;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_GetSyncInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetTime
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GrowSpace
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GrowSpace
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Int2ExtTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Int2ExtTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsConnected
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsConnected
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewCell
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_NewCell
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewEv
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_NewEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewSeq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_NewSeq
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    Open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    ReadSync
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_ReadSync
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Send
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Send
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SendAt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SendAt
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SendIm
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SendIm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetApplAlarm
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetApplAlarm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetField
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetField
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetFilter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetFilter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetInfo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetInfo
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetPortState
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetPortState
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetRcvAlarm
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetRcvAlarm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetSyncMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_SetSyncMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Share
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Share
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    Smpte2Time
 * Signature: (Lgrame/midishare/SmpteLoc;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Smpte2Time
  (JNIEnv *, jclass, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    Task
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Task
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Time2Smpte
 * Signature: (IILgrame/midishare/SmpteLoc;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Time2Smpte
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    TotalSpace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_TotalSpace
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    WriteSync
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_WriteSync
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetLink
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetLink
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetLink
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetLink
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetDate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetDate
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetDate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetDate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetRefnum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetRefnum
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetRefnum
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetRefnum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetType
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetType
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetChan
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetChan
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetChan
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetChan
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetPort
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetPort
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData0
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData1
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData2
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData3
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData3
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData1
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData1
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData2
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData3
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData3
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_grame_midishare_Midi_GetText
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetText
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetText
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetFirstEv
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetFirstEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetFirstEv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetFirstEv
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetLastEv
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetLastEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetLastEv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetLastEv
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewFilter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_NewFilter
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeFilter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeFilter
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AcceptPort
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AcceptPort
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AcceptChan
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AcceptChan
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AcceptType
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AcceptType
  (JNIEnv *, jclass, jint, jint, jint);


/*
 * Class:     grame_midishare_Midi
 * Method:    IsAcceptedPort
 * Signature: (II)I
 */

JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsAcceptedPort
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsAcceptedChan
 * Signature: (II)I
 */


JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsAcceptedChan
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsAcceptedType
 * Signature: (II)I
 */


JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsAcceptedType
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountDrivers
 * Signature: ()I
 */


JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountDrivers
	(JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetIndDriver
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetIndDriver
	(JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetDriverInfos
 * Signature: (ILgrame/midishare/DriverInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetDriverInfos
	(JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    AddSlot
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_AddSlot
	(JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetIndSlot
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetIndSlot
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    RemoveSlot
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_RemoveSlot
	(JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetSlotInfos
 * Signature: (ILgrame/midishare/SlotInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetSlotInfos
	(JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    ConnectSlot
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ConnectSlot
	(JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsSlotConnected
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsSlotConnected
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetSlotName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetSlotName
	(JNIEnv *, jclass, jint, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    WriteEv
 * Signature: (Lgrame/midishare/WriteEvInfo;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_WriteEv
  (JNIEnv *, jclass, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    ReadEv
 * Signature: (Lgrame/midishare/ReadEvInfo;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_ReadEv
  (JNIEnv *, jclass, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewString
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_NewString
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeString
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeString
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    WriteChar
 * Signature: (IIB)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_WriteChar
  (JNIEnv *, jclass, jint, jint, jbyte);

/*
 * Class:     grame_midishare_Midi
 * Method:    ReadChar
 * Signature: (II)B
 */
JNIEXPORT jbyte JNICALL Java_grame_midishare_Midi_ReadChar
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
