/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grame_midishare_Midi */

#ifndef _Included_grame_midishare_Midi
#define _Included_grame_midishare_Midi
#ifdef __cplusplus
extern "C" {
#endif
#undef grame_midishare_Midi_typeNote
#define grame_midishare_Midi_typeNote 0L
#undef grame_midishare_Midi_typeKeyOn
#define grame_midishare_Midi_typeKeyOn 1L
#undef grame_midishare_Midi_typeKeyOff
#define grame_midishare_Midi_typeKeyOff 2L
#undef grame_midishare_Midi_typeKeyPress
#define grame_midishare_Midi_typeKeyPress 3L
#undef grame_midishare_Midi_typeCtrlChange
#define grame_midishare_Midi_typeCtrlChange 4L
#undef grame_midishare_Midi_typeProgChange
#define grame_midishare_Midi_typeProgChange 5L
#undef grame_midishare_Midi_typeChanPress
#define grame_midishare_Midi_typeChanPress 6L
#undef grame_midishare_Midi_typePitchWheel
#define grame_midishare_Midi_typePitchWheel 7L
#undef grame_midishare_Midi_typeSongPos
#define grame_midishare_Midi_typeSongPos 8L
#undef grame_midishare_Midi_typeSongSel
#define grame_midishare_Midi_typeSongSel 9L
#undef grame_midishare_Midi_typeClock
#define grame_midishare_Midi_typeClock 10L
#undef grame_midishare_Midi_typeStart
#define grame_midishare_Midi_typeStart 11L
#undef grame_midishare_Midi_typeContinue
#define grame_midishare_Midi_typeContinue 12L
#undef grame_midishare_Midi_typeStop
#define grame_midishare_Midi_typeStop 13L
#undef grame_midishare_Midi_typeTune
#define grame_midishare_Midi_typeTune 14L
#undef grame_midishare_Midi_typeActiveSens
#define grame_midishare_Midi_typeActiveSens 15L
#undef grame_midishare_Midi_typeReset
#define grame_midishare_Midi_typeReset 16L
#undef grame_midishare_Midi_typeSysEx
#define grame_midishare_Midi_typeSysEx 17L
#undef grame_midishare_Midi_typeStream
#define grame_midishare_Midi_typeStream 18L
#undef grame_midishare_Midi_typePrivate
#define grame_midishare_Midi_typePrivate 19L
#undef grame_midishare_Midi_typeProcess
#define grame_midishare_Midi_typeProcess 128L
#undef grame_midishare_Midi_typeDProcess
#define grame_midishare_Midi_typeDProcess 129L
#undef grame_midishare_Midi_typeQFrame
#define grame_midishare_Midi_typeQFrame 130L
#undef grame_midishare_Midi_typeCtrl14b
#define grame_midishare_Midi_typeCtrl14b 131L
#undef grame_midishare_Midi_typeNonRegParam
#define grame_midishare_Midi_typeNonRegParam 132L
#undef grame_midishare_Midi_typeRegParam
#define grame_midishare_Midi_typeRegParam 133L
#undef grame_midishare_Midi_typeSeqNum
#define grame_midishare_Midi_typeSeqNum 134L
#undef grame_midishare_Midi_typeText
#define grame_midishare_Midi_typeText 135L
#undef grame_midishare_Midi_typeCopyright
#define grame_midishare_Midi_typeCopyright 136L
#undef grame_midishare_Midi_typeSeqName
#define grame_midishare_Midi_typeSeqName 137L
#undef grame_midishare_Midi_typeInstrName
#define grame_midishare_Midi_typeInstrName 138L
#undef grame_midishare_Midi_typeLyric
#define grame_midishare_Midi_typeLyric 139L
#undef grame_midishare_Midi_typeMarker
#define grame_midishare_Midi_typeMarker 140L
#undef grame_midishare_Midi_typeCuePoint
#define grame_midishare_Midi_typeCuePoint 141L
#undef grame_midishare_Midi_typeChanPrefix
#define grame_midishare_Midi_typeChanPrefix 142L
#undef grame_midishare_Midi_typeEndTrack
#define grame_midishare_Midi_typeEndTrack 143L
#undef grame_midishare_Midi_typeTempo
#define grame_midishare_Midi_typeTempo 144L
#undef grame_midishare_Midi_typeSMPTEOffset
#define grame_midishare_Midi_typeSMPTEOffset 145L
#undef grame_midishare_Midi_typeTimeSign
#define grame_midishare_Midi_typeTimeSign 146L
#undef grame_midishare_Midi_typeKeySign
#define grame_midishare_Midi_typeKeySign 147L
#undef grame_midishare_Midi_typeSpecific
#define grame_midishare_Midi_typeSpecific 148L
#undef grame_midishare_Midi_typePortPrefix
#define grame_midishare_Midi_typePortPrefix 149L
#undef grame_midishare_Midi_typeRcvAlarm
#define grame_midishare_Midi_typeRcvAlarm 150L
#undef grame_midishare_Midi_typeApplAlarm
#define grame_midishare_Midi_typeApplAlarm 151L
#undef grame_midishare_Midi_typeReserved
#define grame_midishare_Midi_typeReserved 152L
#undef grame_midishare_Midi_typeDead
#define grame_midishare_Midi_typeDead 255L
#undef grame_midishare_Midi_NoteOff
#define grame_midishare_Midi_NoteOff 128L
#undef grame_midishare_Midi_NoteOn
#define grame_midishare_Midi_NoteOn 144L
#undef grame_midishare_Midi_PolyTouch
#define grame_midishare_Midi_PolyTouch 160L
#undef grame_midishare_Midi_ControlChg
#define grame_midishare_Midi_ControlChg 176L
#undef grame_midishare_Midi_ProgramChg
#define grame_midishare_Midi_ProgramChg 192L
#undef grame_midishare_Midi_AfterTouch
#define grame_midishare_Midi_AfterTouch 208L
#undef grame_midishare_Midi_PitchBend
#define grame_midishare_Midi_PitchBend 224L
#undef grame_midishare_Midi_SysRealTime
#define grame_midishare_Midi_SysRealTime 240L
#undef grame_midishare_Midi_SysEx
#define grame_midishare_Midi_SysEx 240L
#undef grame_midishare_Midi_QFrame
#define grame_midishare_Midi_QFrame 241L
#undef grame_midishare_Midi_SongPos
#define grame_midishare_Midi_SongPos 242L
#undef grame_midishare_Midi_SongSel
#define grame_midishare_Midi_SongSel 243L
#undef grame_midishare_Midi_UnDef2
#define grame_midishare_Midi_UnDef2 244L
#undef grame_midishare_Midi_UnDef3
#define grame_midishare_Midi_UnDef3 245L
#undef grame_midishare_Midi_Tune
#define grame_midishare_Midi_Tune 246L
#undef grame_midishare_Midi_EndSysX
#define grame_midishare_Midi_EndSysX 247L
#undef grame_midishare_Midi_MClock
#define grame_midishare_Midi_MClock 248L
#undef grame_midishare_Midi_UnDef4
#define grame_midishare_Midi_UnDef4 249L
#undef grame_midishare_Midi_MStart
#define grame_midishare_Midi_MStart 250L
#undef grame_midishare_Midi_MCont
#define grame_midishare_Midi_MCont 251L
#undef grame_midishare_Midi_MStop
#define grame_midishare_Midi_MStop 252L
#undef grame_midishare_Midi_UnDef5
#define grame_midishare_Midi_UnDef5 253L
#undef grame_midishare_Midi_ActSense
#define grame_midishare_Midi_ActSense 254L
#undef grame_midishare_Midi_MReset
#define grame_midishare_Midi_MReset 255L
#undef grame_midishare_Midi_errSpace
#define grame_midishare_Midi_errSpace -1L
#undef grame_midishare_Midi_errRefNum
#define grame_midishare_Midi_errRefNum -2L
#undef grame_midishare_Midi_errBadType
#define grame_midishare_Midi_errBadType -3L
#undef grame_midishare_Midi_errIndex
#define grame_midishare_Midi_errIndex -4L
#undef grame_midishare_Midi_SyncExternal
#define grame_midishare_Midi_SyncExternal 32768L
#undef grame_midishare_Midi_SyncAnyPort
#define grame_midishare_Midi_SyncAnyPort 16384L
#undef grame_midishare_Midi_OpenAppl
#define grame_midishare_Midi_OpenAppl 1L
#undef grame_midishare_Midi_CloseAppl
#define grame_midishare_Midi_CloseAppl 2L
#undef grame_midishare_Midi_ChgName
#define grame_midishare_Midi_ChgName 3L
#undef grame_midishare_Midi_ChgConnect
#define grame_midishare_Midi_ChgConnect 4L
#undef grame_midishare_Midi_OpenModem
#define grame_midishare_Midi_OpenModem 5L
#undef grame_midishare_Midi_CloseModem
#define grame_midishare_Midi_CloseModem 6L
#undef grame_midishare_Midi_OpenPrinter
#define grame_midishare_Midi_OpenPrinter 7L
#undef grame_midishare_Midi_ClosePrinter
#define grame_midishare_Midi_ClosePrinter 8L
#undef grame_midishare_Midi_SyncStart
#define grame_midishare_Midi_SyncStart 9L
#undef grame_midishare_Midi_SyncStop
#define grame_midishare_Midi_SyncStop 10L
#undef grame_midishare_Midi_ChangeSync
#define grame_midishare_Midi_ChangeSync 11L
#undef grame_midishare_Midi_OpenDriver
#define grame_midishare_Midi_OpenDriver 12L
#undef grame_midishare_Midi_CloseDriver
#define grame_midishare_Midi_CloseDriver 13L
#undef grame_midishare_Midi_AddSlot
#define grame_midishare_Midi_AddSlot 14L
#undef grame_midishare_Midi_RemoveSlot
#define grame_midishare_Midi_RemoveSlot 15L
#undef grame_midishare_Midi_ChgSlotConnect
#define grame_midishare_Midi_ChgSlotConnect 16L
#undef grame_midishare_Midi_ChgSlotName
#define grame_midishare_Midi_ChgSlotName 17L
#undef grame_midishare_Midi_InputSlot
#define grame_midishare_Midi_InputSlot 1L
#undef grame_midishare_Midi_OutputSlot
#define grame_midishare_Midi_OutputSlot 2L
#undef grame_midishare_Midi_InputOutputSlot
#define grame_midishare_Midi_InputOutputSlot 3L
/*
 * Class:     grame_midishare_Midi
 * Method:    AddField
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AddField
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AddSeq
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AddSeq
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    ApplySeq
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ApplySeq
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    AvailEv
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_AvailEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Call
 * Signature: (JJIIII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Call
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    ClearSeq
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ClearSeq
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    Close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Close
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Connect
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Connect
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CopyEv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_CopyEv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountAppls
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountAppls
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountDTasks
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountDTasks
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountEvs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountEvs
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountFields
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountFields
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    DTask
 * Signature: (JJIIII)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_DTask
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Exec1DTask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Exec1DTask
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Ext2IntTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_Ext2IntTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    FlushDTasks
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FlushDTasks
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    FlushEvs
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FlushEvs
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    ForgetTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ForgetTask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeCell
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeCell
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeEv
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeEv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeSeq
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeSeq
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeSpace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_FreeSpace
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetApplAlarm
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetApplAlarm
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetEv
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetExtTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetExtTime
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetField
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetField
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetFilter
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetFilter
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetIndAppl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetIndAppl
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetInfo
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_grame_midishare_Midi_GetName
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetNamedAppl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetNamedAppl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetPortState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetPortState
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetRcvAlarm
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetRcvAlarm
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetSyncInfo
 * Signature: (Lgrame/midishare/SyncInfo;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_GetSyncInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetTime
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GrowSpace
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GrowSpace
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Int2ExtTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_Int2ExtTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsConnected
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsConnected
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewCell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_NewCell
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewEv
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_NewEv
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewSeq
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_NewSeq
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    Open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    ReadSync
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_ReadSync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    Send
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Send
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SendAt
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SendAt
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SendIm
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SendIm
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetApplAlarm
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetApplAlarm
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetField
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetField
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetFilter
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetFilter
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetInfo
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetInfo
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetPortState
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetPortState
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetRcvAlarm
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetRcvAlarm
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetSyncMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_SetSyncMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Smpte2Time
 * Signature: (Lgrame/midishare/SmpteLoc;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_Smpte2Time
  (JNIEnv *, jclass, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    Task
 * Signature: (JJIIII)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_Task
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    Time2Smpte
 * Signature: (JILgrame/midishare/SmpteLoc;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_Time2Smpte
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    TotalSpace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_TotalSpace
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    WriteSync
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_WriteSync
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetLink
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetLink
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetLink
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetLink
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetDate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetDate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetDate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetDate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetRefnum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetRefnum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetRefnum
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetRefnum
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetChan
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetChan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetChan
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetChan
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetPort
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetPort
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetData3
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetData3
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData1
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData2
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData2
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetData3
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetData3
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_grame_midishare_Midi_GetText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetFirstEv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetFirstEv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetFirstEv
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetFirstEv
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetLastEv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_GetLastEv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetLastEv
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetLastEv
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    NewFilter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_Midi_NewFilter
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    FreeFilter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_FreeFilter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     grame_midishare_Midi
 * Method:    AcceptPort
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AcceptPort
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AcceptChan
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AcceptChan
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    AcceptType
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_AcceptType
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsAcceptedPort
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsAcceptedPort
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsAcceptedChan
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsAcceptedChan
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsAcceptedType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsAcceptedType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    CountDrivers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_CountDrivers
  (JNIEnv *, jclass);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetIndDriver
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetIndDriver
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetDriverInfos
 * Signature: (ILgrame/midishare/DriverInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetDriverInfos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    AddSlot
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_AddSlot
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetIndSlot
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetIndSlot
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    RemoveSlot
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_RemoveSlot
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    GetSlotInfos
 * Signature: (ILgrame/midishare/SlotInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_GetSlotInfos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    ConnectSlot
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_ConnectSlot
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    IsSlotConnected
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_IsSlotConnected
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_Midi
 * Method:    SetSlotName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_Midi_SetSlotName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     grame_midishare_Midi
 * Method:    WriteEv
 * Signature: (Lgrame/midishare/WriteEvInfo;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_WriteEv
  (JNIEnv *, jclass, jobject);

/*
 * Class:     grame_midishare_Midi
 * Method:    ReadEv
 * Signature: (Lgrame/midishare/ReadEvInfo;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_Midi_ReadEv
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
