/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grame_midishare_MidiAppl */

#ifndef _Included_grame_midishare_MidiAppl
#define _Included_grame_midishare_MidiAppl
#ifdef __cplusplus
extern "C" {
#endif
#undef grame_midishare_MidiAppl_typeTask
#define grame_midishare_MidiAppl_typeTask 19L
#undef grame_midishare_MidiAppl_typeAlarm
#define grame_midishare_MidiAppl_typeAlarm 20L
#undef grame_midishare_MidiAppl_kPollingMode
#define grame_midishare_MidiAppl_kPollingMode 0L
#undef grame_midishare_MidiAppl_kNativeMode
#define grame_midishare_MidiAppl_kNativeMode 1L
/*
 * Class:     grame_midishare_MidiAppl
 * Method:    ApplOpen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_MidiAppl_ApplOpen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     grame_midishare_MidiAppl
 * Method:    ApplClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_MidiAppl_ApplClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     grame_midishare_MidiAppl
 * Method:    ScheduleTask
 * Signature: (Lgrame/midishare/MidiTask;JII)J
 */
JNIEXPORT jlong JNICALL Java_grame_midishare_MidiAppl_ScheduleTask
  (JNIEnv *, jobject, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
