#!/bin/sh
#


host=$(uname)

if [ $host = Darwin ] 
then
	cmake -G Xcode $*
elif [ $host = Linux ]
then
	cmake -G "CodeBlocks - Unix Makefiles" $*
else
	if [ "$1" = "WIN64" ]
	then
		shift
		dir=../vs2005_64
		gen="Visual Studio 8 2005 Win64"
	else
		dir=../vs2005
		gen="Visual Studio 8 2005"
	fi
	[ -d $dir ] || mkdir $dir
	cp CMakeLists.txt $dir
	cd $dir && cmake -G "$gen"  $*
fi
