
TARGET = msApplsLib.o
CFLAGS := $(CFLAGS) -I../../Include `gtk-config --cflags`
#CFLAGS := -I../../Include -Wall -O6 `gtk-config --cflags`
OBJ  = msApplsTools.o
#CC   = gcc

all : $(TARGET)
  
$(TARGET) : $(OBJ)
	ld -m elf_i386 -r -o $(TARGET) $(OBJ)

clean :
	rm -f $(TARGET) $(OBJ)
	
