
TARGET = ../linux/lib/mskUtilities.o
OPTIONS = -D__Pentium__ -DMODULE -D_LOOSE_KERNEL_NAMES -DCONFIG_KERNELD 
INC = -I../linux/Include -I../common/Headers
CFLAGS := -O6 -Wall $(OPTIONS) $(INC)
CC = gcc


SRC = k*.c
OBJ = kMidiPrint.o kEventToMidiStream.o kMidiStreamToEvent.o kmsDrvUtils.o 

$(TARGET) : $(OBJ)
	ld -m elf_i386 -r -o $(TARGET) $(OBJ)

dep:
	makedepend -f module -- $(CFLAGS) -- -Y -m $(SRC)

clean:
	rm $(OBJ) $(TARGET)


# DO NOT DELETE
