
SRC = $(wildcard unix/*.cpp glue/*.cpp *.cpp)
OBJ = $(patsubst %.cpp, %.o, $(SRC))

CFLAGS = -O3 -Iinclude -Iglue -Wall
CXXFLAGS = $(CFLAGS)
CXX = c++

OUT = ../msOSGlueLib.o

all: makefile $(OUT)

$(OUT) : $(OBJ)
	ld -r -o $(OUT) $(OBJ)

makefile: makefile.osx
	cp -f makefile.osx makefile
	rm -f $(OBJ) $(OUT)

clean:
	rm -f $(OBJ) $(OUT)

dep:
	makedepend -- $(CFLAGS) -- -Y -m $(SRC)

