
SRC = $(wildcard unix/*.cpp glue/*.cpp *.cpp)
OBJ = $(patsubst %.cpp, %.o, $(SRC))

CFLAGS = -O3 -Iinclude -Iglue -Wall
CXXFLAGS = $(CFLAGS)
CXX = c++

OUT = ../msOSGlueLib.o

all: makefile $(OUT)

$(OUT) : $(OBJ)
	ld -r -o $(OUT) $(OBJ)

makefile: makefile.osx
	cp -f makefile.osx makefile
	rm -f $(OBJ) $(OUT)
	make dep

clean:
	rm -f $(OBJ) $(OUT)

dep:
	mkdep -f __dep__ $(CFLAGS) $(SRC)
	cat makefile.osx __dep__ > makefile
	rm -f __dep__

