
SRC = $(wildcard unix/*.cpp *.cpp)
OBJ = $(patsubst %.cpp, %.o, $(SRC))

CFLAGS = -O3 -Iinclude -Wall
CXXFLAGS = $(CFLAGS)
CC = g++

OUT = ../msOSGlueLib.o

all: makefile $(OUT)

$(OUT) : $(OBJ)
	ld -r -o $(OUT) $(OBJ)

makefile: makefile.linux
	cp -f makefile.linux makefile
	rm -f $(OBJ) $(OUT)
	make dep

clean:
	rm -f $(OBJ) $(OUT)

dep:
	makedepend -- $(CFLAGS) -- -Y -m $(SRC)

