
SRC = $(wildcard unix/*.cpp glue/*.cpp *.cpp)
OBJ = $(patsubst %.cpp, %.o, $(SRC))

CFLAGS = -O3 -Iinclude -Iglue -Wall
CXXFLAGS = $(CFLAGS)
CC = gcc

OUT = ../msOSGlueLib.o

all: makefile $(OUT)

$(OUT) : $(OBJ)
	ld -m elf_i386 -r -o $(OUT) $(OBJ)

makefile: makefile.linux
	cp -f makefile.linux makefile
	rm -f $(OBJ) $(OUT)

clean:
	rm -f $(OBJ) $(OUT)

dep:
	makedepend -- $(CFLAGS) -- -Y -m $(SRC)

