#!/bin/sh
#

. ./content

function remove () {
	f=$2/$1
	if [ -a $f ] 
	then
		echo remove $f
		rm -rf $f
	fi
}

remove MidiShare.framework $DIST/System/Library/Frameworks

for a in $appls
do
	remove $(basename $a) $DIST/Applications/MidiShare
done

for a in $drivers
do
	remove $(basename $a) $DIST/usr/lib
done


exit 0
