#!/bin/sh
#

h=$(pwd)

echo save distribution tree
[ -d Distribution.save ] && rm -rf Distribution.save
mv Distribution Distribution.save
cp -R Distribution.save Distribution

echo "creation des liens symboliques (dylib)"
./linklibs

echo suppression des dossiers CVS
rm -f $(find Distribution -type d -name CVS)

echo remove the .DS_Store files
rm -f $(find Distribution -name ".DS_Store")

echo generates install.log
cd Distribution
find . -depth -print | sed -e 's/^\.//' > ../install.log
mv -f ../install.log Applications/MidiShare
cd ..

echo verification des droits des fichiers et des dossiers
find Distribution -type d -exec chmod 755 {} \;
find Distribution -type f -exec chmod g+w {} \;
find Distribution -type f -exec chmod o-w {} \;

chown -R root:wheel private
chown -R root:wheel Distribution/*
chown -R root:admin Distribution/Applications/*

chmod 775 Distribution/Applications
chmod 775 Distribution/System

echo "protection des fichiers .ini"
cd private/etc/MidiShare/defaults
chmod go-w *
