#!/bin/sh
#

ilog=/Applications/MidiShare/install.log

drvs=$(grep "/usr/lib" $ilog | grep ".so")
jni=$(grep "/usr/lib" $ilog | grep ".jnilib")

jar=/Library/Java/Extensions/grame.jar
MidiShare=/Applications/MidiShare
user=$HOME/Library/Preferences/MidiShare
framework="/System/Library/Frameworks/MidiShare.framework /System/Library/Frameworks/Player.framework"
etc="/private/etc/MidiShare"

TRASH=$HOME/.Trash

function uninstall {
	for a in $*
	do
		[ -a $a ] && sudo mv -f $a $TRASH
	done
}

uninstall $drvs
uninstall $jni
uninstall $MidiShare
uninstall $framework
uninstall $user
uninstall $etc

exit 0
