#!/bin/sh
#

#n="1 2 3 4 5 6 7 8 9 10 15 20"
n=$*
outdirs=bench
outfile=bench
outdrv=msBenchDriver
outkrn=msKernelTimeBench

function bench() {
	count=$1
	dir=$outdirs-$1
	[ -d $dir ] || mkdir $dir
	while [ $count -gt 0 ]
	do
		./msBenchAppl > $dir/$outfile-$count.out.txt 2>  $dir/$outfile-$count.sum.txt &
#		./msBenchAppl > $dir/$outfile-$count.out.txt &
		count=$(($count - 1))
	done
#	sleep $(($1 + 1))
	sleep 5
	[ -f $outdrv.out.txt ] && mv $outdrv.*.txt $dir
	[ -f $outkrn.txt ] && mv $outkrn.* $dir
}

MidiShare || exit 1

for a in $n
do
	echo bench with $a client
	bench $a
done

echo end of bench
