.TH MSALSASEQ 1 "May 2004" "" "MidiShare User's Manual"
.SH NAME
.B msAlsaSeq
- ALSA driver for MidiShare
.SH SYNOPSIS
.BI "msAlsaSeq [" options "] [" client-name "]"
.SH DESCRIPTION
.B msAlsaSeq
creates an ALSA client and a corresponding MidiShare client, both named
.I client-name
("MidiShare/ALSA Bridge" by default) and establishes connections to other
ALSA clients as given by the
.B -i
and
.B -o
options. Input from port 0 of the ALSA client will be mapped to the MidiShare
client, and output from the MidiShare client will be mapped to port 1 of the
ALSA client. This allows you to access ALSA devices and other ALSA clients
from MidiShare applications.
.PP
You can just start the program as
.B msAlsaSeq
and establish connections to other ALSA clients manually with
.BR aconnect (1)
or your favourite ALSA patchbay. Alternatively, you can specify the desired
connections directly on the command line. For instance,
.sp
.nf
         msAlsaSeq -i 64:0 -o 64:0
.fi
.sp
connects input and output to port 0 of client 64 (usually this corresponds to
the external MIDI interface of your first soundcard).
.PP
Instead of a numeric ALSA client id, you can also specify the client's
name. Shell wildcards (`*', `?' etc.)  are recognized as well. E.g.,
.sp
.nf
        msAlsaSeq -i 'Rawmidi*':0
.fi
.sp
connects the input to port 0 of the first client whose name starts with
`Rawmidi'. To find out about the available ALSA sequencer clients and ports on
your system, run the ALSA
.B aconnect
program with the
.B -i
and
.B -o
options. You can also use the MidiShare
.B msconnect
program to connect your MidiShare applications with the MidiShare client
created by
.BR msAlsaSeq .
Multiple instances of
.B msAlsaSeq
can be run to access different ALSA clients. In this case it is useful to
specify the
.I client-name
parameter to distinguish between the different clients. Example:
.sp
.nf
         msAlsaSeq "ALSA Midi Port" -i 64:0 -o 64:0
         msAlsaSeq "ALSA Wavetable Synth" -o 65:0
.fi
.sp
.SH OPTIONS
.TP
.B -h
Prints a short usage message and exit.
.TP
.BI -i " client" : port
Establishes an input connection with the given ALSA client and port. The
client can be given either by its numeric id or a pattern for the client name.
.TP
.BI -o " client" : port
Establishes an output connection.
.SH NOTES
Currently
.B msAlsaSeq
does not keep track of the original ALSA timestamps and client/port
numbers. The timestamp of a received event indicates the time at which the
event was read by the driver. The MidiShare port number of a received event is
always zero, and transmitted events are always sent to all connected ALSA
clients, no matter which MidiShare port was specified.
.SH "SEE ALSO"
aconnect(1), http://www.grame.fr/MidiShare
