#!/bin/sh
#

. ./content

case $1 in 
	"dist")
		echo remove the .DS_Store files
		find $DIST -name ".DS_Store" -exec rm -rf {} \;
		
		echo generates install.log
		./makeLog instlog > install.log
		mv install.log $DIST/Applications/MidiShare
		
		echo change rights
		find $DIST -type d -exec chmod 755 {} \;
		find $DIST -type f -exec chmod g+w {} \;
		find $DIST -type f -exec chmod o-w {} \;
		
		chmod 775 $DIST/Applications
		chmod 775 $DIST/System
		
		echo change owner
		chown -R root:wheel $DIST/private
		chown -R root:wheel $DIST/*
		chown -R root:admin $DIST/Applications/*
		
		echo "protect .ini files"
		chmod go-w $DIST/private/etc/MidiShare/defaults/*
		;;

	"dev")
		echo generates dev install.log
		./makeLog devlog > install.log
		mv install.log $DEV/Applications/MidiShare/Developer
		
		echo change dev rights
		find $DEV -type d -exec chmod 755 {} \;
		find $DEV -type f -exec chmod g+w {} \;
		find $DEV -type f -exec chmod o-w {} \;
		
		echo change dev owner
		chown -R root:wheel $DEV
		;;

	*)
		echo "finalize: undefined target"
		echo "usage: finalize [ dist | dev ]"
		;;
esac
