#!/bin/sh
#

h=$(pwd)

D=Distribution

APPLS=Applications
JAVA=Library/Java/Extensions
ETC=private/etc
SYSTEM=System/Library/Frameworks
USR=usr/lib/java

echo save distribution tree
[ -d Distribution.save ] && rm -rf Distribution.save
mv Distribution Distribution.save
cp -R Distribution.save Distribution

echo suppression des dossiers CVS
find Distribution -depth -type d -name CVS -exec rm -rf {} \;

echo remove the .DS_Store files
find Distribution -name ".DS_Store" -exec rm -rf {} \;

echo generates install.log
./scripts/makeLog > install.log
mv install.log Distribution/Applications/MidiShare

echo verification des droits des fichiers et des dossiers
find Distribution -type d -exec chmod 755 {} \;
find Distribution -type f -exec chmod g+w {} \;
find Distribution -type f -exec chmod o-w {} \;

chown -R root:wheel private
chown -R root:wheel Distribution/*
chown -R root:admin Distribution/Applications/*

chmod 775 Distribution/Applications
chmod 775 Distribution/System

echo "protection des fichiers .ini"
chmod go-w Distribution/private/etc/MidiShare/defaults/*
