/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grame_midishare_player_MidiPlayer */

#ifndef _Included_grame_midishare_player_MidiPlayer
#define _Included_grame_midishare_player_MidiPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    OpenAux
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_OpenAux
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_Close
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_Start
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Cont
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_Cont
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_Pause
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetRecordMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetRecordMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Record
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_Record
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetRecordFilter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetRecordFilter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetPosBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetPosBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetPosMs
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetPosMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetLoop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetLoop
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetLoopStartBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_SetLoopStartBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetLoopEndBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_SetLoopEndBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetLoopStartMs
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_SetLoopStartMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetLoopEndMs
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_SetLoopEndMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetSynchroIn
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetSynchroIn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetSynchroOut
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetSynchroOut
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetTempo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetTempo
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetSMPTEOffset
 * Signature: (ILgrame/midishare/SmpteLoc;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetSMPTEOffset
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    GetState
 * Signature: (ILgrame/midishare/player/PlayerState;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_GetState
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    GetEndScore
 * Signature: (ILgrame/midishare/player/PlayerState;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_GetEndScore
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    ForwardStep
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_ForwardStep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    BackwardStep
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_BackwardStep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    GetAllTrack
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_GetAllTrack
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    GetTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_GetTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_SetTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetAllTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_SetAllTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    SetParam
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer_SetParam
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    GetParam
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_GetParam
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    InsertAllTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_InsertAllTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    InsertTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_InsertTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Load
 * Signature: (Ljava/lang/String;ILgrame/midishare/midifile/MidiFileInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_Load
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer
 * Method:    Save
 * Signature: (Ljava/lang/String;ILgrame/midishare/midifile/MidiFileInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer_Save
  (JNIEnv *, jclass, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
