/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grame_midishare_player_MidiPlayer2 */

#ifndef _Included_grame_midishare_player_MidiPlayer2
#define _Included_grame_midishare_player_MidiPlayer2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    OpenAux
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_OpenAux
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_Close
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_Start
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Cont
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_Cont
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_Pause
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetRecordMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetRecordMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Record
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_Record
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetRecordFilter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetRecordFilter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetPosBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetPosBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetPosMs
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetPosMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetPosTicks
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetPosTicks
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetLoop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetLoop
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetLoopStartBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_SetLoopStartBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetLoopEndBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_SetLoopEndBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetLoopStartMs
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_SetLoopStartMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetLoopEndMs
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_SetLoopEndMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetSynchroIn
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetSynchroIn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetSynchroOut
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetSynchroOut
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetTempo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetTempo
  (JNIEnv *, jclass, jint, jint);
  
/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetTempoFactor
 * Signature: (IF)V
 */

JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetTempoFactor
	(JNIEnv *, jclass, jint, jfloat);


/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetSMPTEOffset
 * Signature: (ILgrame/midishare/SmpteLoc;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetSMPTEOffset
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    GetState
 * Signature: (ILgrame/midishare/player/PlayerState;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_GetState
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    GetEndScore
 * Signature: (ILgrame/midishare/player/PlayerState;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_GetEndScore
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    ForwardStep
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_ForwardStep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    BackwardStep
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_BackwardStep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    GetAllTrack
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_GetAllTrack
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    GetTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_GetTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_SetTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetAllTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_SetAllTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    SetParam
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer2_SetParam
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    GetParam
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_GetParam
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    InsertAllTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_InsertAllTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    InsertTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_InsertTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Load
 * Signature: (Ljava/lang/String;ILgrame/midishare/midifile/MidiFileInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_Load
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer2
 * Method:    Save
 * Signature: (Ljava/lang/String;ILgrame/midishare/midifile/MidiFileInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer2_Save
  (JNIEnv *, jclass, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
