/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grame_midishare_player_MidiPlayer1 */

#ifndef _Included_grame_midishare_player_MidiPlayer1
#define _Included_grame_midishare_player_MidiPlayer1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    OpenAux
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_OpenAux
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_Close
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_Start
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Cont
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_Cont
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_Pause
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetRecordMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetRecordMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Record
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_Record
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetRecordFilter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetRecordFilter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetPosBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetPosBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetPosMs
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetPosMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetLoop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetLoop
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetLoopStartBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_SetLoopStartBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetLoopEndBBU
 * Signature: (ILgrame/midishare/player/PlayerPos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_SetLoopEndBBU
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetLoopStartMs
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_SetLoopStartMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetLoopEndMs
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_SetLoopEndMs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetSynchroIn
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetSynchroIn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetSynchroOut
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetSynchroOut
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetTempo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetTempo
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetSMPTEOffset
 * Signature: (ILgrame/midishare/SmpteLoc;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetSMPTEOffset
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    GetState
 * Signature: (ILgrame/midishare/player/PlayerState;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_GetState
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    GetEndScore
 * Signature: (ILgrame/midishare/player/PlayerState;)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_GetEndScore
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    ForwardStep
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_ForwardStep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    BackwardStep
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_BackwardStep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    GetAllTrack
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_GetAllTrack
  (JNIEnv *, jclass, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    GetTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_GetTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_SetTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetAllTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_SetAllTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    SetParam
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetParam
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    GetParam
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_GetParam
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    InsertAllTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_InsertAllTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    InsertTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_InsertTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Load
 * Signature: (Ljava/lang/String;ILgrame/midishare/midifile/MidiFileInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_Load
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     grame_midishare_player_MidiPlayer1
 * Method:    Save
 * Signature: (Ljava/lang/String;ILgrame/midishare/midifile/MidiFileInfos;)I
 */
JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_Save
  (JNIEnv *, jclass, jstring, jint, jobject);
  
  
  

JNIEXPORT void JNICALL Java_grame_midishare_player_MidiPlayer1_SetEventProducer
   (JNIEnv *, jclass, jint, jint);

JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_GetEventProducer
  (JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_MakeScoreProducer
  (JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_MakeSeqProducer
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_MakeMixProducer
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_MakeReactiveProducer
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT jint JNICALL Java_grame_midishare_player_MidiPlayer1_MakeEventFilter
  (JNIEnv *, jclass, jint );


#ifdef __cplusplus
}
#endif
#endif
