
TARGET = ../macosx-mono/msCommon.o
OPTIONS = -D__Macintosh__ -D__POWERPC__ -D__MacOSX__
INC = -I Headers -I atomic
CFLAGS :=  -O3 -Wall $(OPTIONS) $(INC)
CC = cc

A = atomic
C = Clients
K = Kernel
M = Memory
S = Sorter
D = Drivers

SRC = $(wildcard $(A)/*ifo.c $(C)/*.c $(K)/*.c $(M)/*.c $(S)/*.c $(D)/*.c)
OBJ := $(patsubst %.c, %.o, $(SRC)) 


$(TARGET) : $(OBJ)
	ld -r -o $(TARGET) $(OBJ)

dep:
	makedepend -- $(CFLAGS) -- -Y -m $(SRC)

clean:
	rm -f $(OBJ) $(TARGET)

# DO NOT DELETE
