.\" Copyright (c) 1999
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiGetVersion.1	1.0 (Grame) 23/09/99
.\"
.TH MIDIGETVERSION 1 "23 September 1999" "" "MidiShare User's Manual"
.SH NAME
.B MidiGetVersion 
- gives the MidiShare version number.
.SH SYNOPSIS
.BI MidiGetVersion  
.SH DESCRIPTION
.B MidiGetVersion
returns the current MidiShare version number. Units and tens should 
be considered as minor version numbers so that for example, the number 
100 is denoting a version 1.00.
.PP

