.\" Copyright (c) 2003
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiGetDriverInfos.1	1.0 (Grame) 20/05/03
.\"
.TH MIDIGETDRIVERINFOS 1 "20 May 2003" "" "MidiShare User's Manual"
.SH NAME
.B MidiGetDriverInfos 
- gives information about a MidiShare driver.
.SH SYNOPSIS
.BI MidiGetDriverInfos " refnum 
.SH DESCRIPTION
.B MidiGetDriverInfos
returns information about a MidiShare driver from is reference
number. Information includes the driver name, its version number 
and its total slots count.
.PP
The refnum argument should be a valid reference number.     
.SH "SEE ALSO"
.BR MidiCountDrivers (1),
.BR MidiGetIndDriver (1),

