.\" Copyright (c) 1999
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiGetName.1	1.0 (Grame) 23/09/99
.\"
.TH MIDIGETNAME 1 "23 September 1999" "" "MidiShare User's Manual"
.SH NAME
.B MidiGetName 
- gives an application name from its reference number.
.SH SYNOPSIS
.BI MidiGetName " refnum 
.SH DESCRIPTION
.B MidiGetName
allows you to get the name of a MidiShare client application from its
reference number. 
.PP
The refnum argument should be a valid reference number.     
.PP
.SH "SEE ALSO"
.BR MidiCountAppls (1),
.BR MidiGetIndAppl (1),

