.\" Copyright (c) 2003
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiCountDrivers.1	1.0 (Grame) 20/05/03
.\"
.TH MIDICOUNTDRIVERS 1 "20 May 2003" "" "MidiShare User's Manual"
.SH NAME
MidiCountDrivers \- returns the MidiShare client drivers count
.SH SYNOPSIS
.BI MidiCountDrivers 
.SH DESCRIPTION
.B MidiCountDrivers
returns the total number of MidiShare drivers running 
(including the MidiShare driver itself).
.PP
.SH "SEE ALSO"
.BR MidiGetIndDriver (1),
.BR MidiGetNamedAppl (1),

