.\" Copyright (c) 1999
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiCountAppls.1	1.0 (Grame) 23/09/99
.\"
.TH MIDICOUNTAPPLS 1 "23 September 1999" "" "MidiShare User's Manual"
.SH NAME
MidiCountAppls \- returns the MidiShare client applications count
.SH SYNOPSIS
.BI MidiCountAppls 
.SH DESCRIPTION
.B MidiCountAppls
returns the total number of MidiShare client applications running 
(including MidiShare itself).
.PP
.SH "SEE ALSO"
.BR MidiGetIndApp (1),
.BR MidiGetNamedAppl (1),

