.\" Copyright (c) 1999
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiGetTime.1	1.0 (Grame) 23/09/99
.\"
.TH MIDIGETTIME 1 "23 September 1999" "" "MidiShare User's Manual"
.SH NAME
.B MidiGetTime 
- gives the current MidiShare time in mls.
.SH SYNOPSIS
.BI MidiGetTime  
.SH DESCRIPTION
.B MidiGetTime
returns the current MidiShare time in milliseconds. 
.PP

