
TARGET = ../../linux/libCommon.o
FLAGS := -O0 -Wall -g -D_REENTRANT -D__Linux__ -D__Pentium__
LOBJ = lib
CC = gcc
LD = ld
CFLAGS := $(FLAGS) -fPIC -I../Headers

OBJ = $(LOBJ)/msMemory.o $(LOBJ)/msEvents.o $(LOBJ)/msSeq.o $(LOBJ)/msMem.o
SRC = msMemory.c msEvents.c msSeq.c msMem.c

$(TARGET) :  $(OBJ)
	$(LD) $(OBJ) -g -fPIC -r -o $(TARGET)

dep:
	makedepend -- $(CFLAGS) -- -p$(LOBJ)/ -Y -m $(SRC)

$(LOBJ)/msMemory.o: msMemory.c
	$(CC) $(CFLAGS) -c msMemory.c -o $(LOBJ)/msMemory.o
$(LOBJ)/msEvents.o: msEvents.c
	$(CC) $(CFLAGS) -c msEvents.c -o $(LOBJ)/msEvents.o
$(LOBJ)/msSeq.o:    msSeq.c
	$(CC) $(CFLAGS) -c msSeq.c -o $(LOBJ)/msSeq.o
$(LOBJ)/msMem.o:    msMem.c
	$(CC) $(CFLAGS) -c msMem.c -o $(LOBJ)/msMem.o

clean : 
	rm $(OBJ) $(TARGET)

# DO NOT DELETE

lib/msMemory.o: ../Headers/msDefs.h ../Headers/msTypes.h
lib/msMemory.o: ../Headers/msMemory.h ../Headers/lflifo.h ../Headers/msSync.h
lib/msMemory.o: ../Headers/msMem.h
lib/msEvents.o: ../Headers/msEvents.h ../Headers/msDefs.h
lib/msEvents.o: ../Headers/msTypes.h ../Headers/lflifo.h ../Headers/msSync.h
lib/msSeq.o: ../Headers/msSeq.h ../Headers/msDefs.h ../Headers/msTypes.h
lib/msSeq.o: ../Headers/lflifo.h ../Headers/msSync.h ../Headers/msEvents.h
lib/msMem.o: ../Headers/msMem.h ../Headers/msTypes.h
