.\" Copyright (c) 1999
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiGetNamedAppl.1	1.0 (Grame) 23/09/99
.\"
.TH MIDIGETNAMEDAPPL 1 "23 September 1999" "" "MidiShare User's Manual"
.SH NAME
.B MidiGetNamedAppl 
- gives the reference number of an application from its name.
.SH SYNOPSIS
.BI MidiGetNamedAppl " name 
.SH DESCRIPTION
.B MidiGetNamedAppl
allows you to get the reference number of a MidiShare client application 
from its name. 
.PP
The name argument should be a valid MidiShare client application name.     
.PP
.SH "SEE ALSO"
.BR MidiGetName (1),

