.\" Copyright (c) 1999
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiConnect.1	1.0 (Grame) 23/09/99
.\"
.TH MIDICONNECT 1 "23 September 1999" "" "MidiShare User's Manual"
.SH NAME
.B MidiConnect 
- connect or disconnect 2 MidiShare client applications
.SH SYNOPSIS
.BI MidiConnect " src dest state 
.SH DESCRIPTION
.B MidiConnect
allows you to make or remove a virtual MIDI connection between 2
MidiShare client applications. 
.PP
src and dest should be valid MidiShare client application names or reference
numbers.     
.PP
state should be in 0, 1 or true, false:
.RS
 \- uses 1 or true to make a connection
 \- uses 0 or false to remove a connection
.RE
.PP
.SH "SEE ALSO"
.BR MidiIsConnected (1),

