.\" Copyright (c) 1999
.\"	Grame - Computer Music Research Laboratory
.\"
.\"     @(#)MidiIsConnect.1	1.0 (Grame) 23/09/99
.\"
.TH MIDIISCONNECTED 1 "23 September 1999" "" "MidiShare User's Manual"
.SH NAME
MidiIsConnected \- gives the connection state of 2 MidiShare client applications
.SH SYNOPSIS
.BI MidiIsConnected " src dest 
.SH DESCRIPTION
.B MidiIsConnected
returns 1 if a virtual MIDI connection between the 2 arguments 
MidiShare client applications exist; otherwise returns 0.
.PP
src and dest should be MidiShare valid client application names or reference
numbers.     
.PP
.PP
.SH "SEE ALSO"
.BR MidiConnect (1),

